language: java
sudo: false
install: true
jdk:
  - oraclejdk8
dist: trusty
before_install:
  - chmod +x gradlew
before_script:
  - >
    git clone https://github.com/fossas/fossa-travisci-plugin;
    cd fossa-travisci-plugin;
    npm i && node index.js;
    cd ../
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
after_success:
  - fossa test
notifications:
  webhooks: https://app.fossa.io/hooks/travisci

before_deploy: ./gradlew prepareUpload
deploy:
  - provider: releases
    file: build/libs/mfsjea.jvm.jar
    skip_cleanup: true
    on:
      repo: RanolP/mfsjea.jvm
      tags: true
  - provider: bintray
    file: .bintraydescriptor.json
    user: ranolp
    skip_cleanup: true
    on:
      repo: RanolP/mfsjea.jvm
      tags: true
