language: java
sudo: false
install: true
jdk:
  - oraclejdk8
dist: trusty
before_install:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash"
  - chmod +x gradlew
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
after_success:
  - fossa test
notifications:
  webhooks: https://app.fossa.io/hooks/travisci
